// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ZraAHcikDfnDPcUN1UEdLrznxnvyANs',
    appId: '1:49266914884:web:1aa4561be2cbca7f392e11',
    messagingSenderId: '49266914884',
    projectId: 'secretcomms-6de0e',
    authDomain: 'secretcomms-6de0e.firebaseapp.com',
    storageBucket: 'secretcomms-6de0e.appspot.com',
    measurementId: 'G-RHKTT32EBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNoJhwdlbjZti552jPTJYn3b4Zqpq8Ue8',
    appId: '1:49266914884:android:11cf6ef390500ffa392e11',
    messagingSenderId: '49266914884',
    projectId: 'secretcomms-6de0e',
    storageBucket: 'secretcomms-6de0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhz_U3D8WCfpit6l1Nkq1zht3U18vzI8I',
    appId: '1:49266914884:ios:d303749789029562392e11',
    messagingSenderId: '49266914884',
    projectId: 'secretcomms-6de0e',
    storageBucket: 'secretcomms-6de0e.appspot.com',
    iosBundleId: 'com.example.secretComms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhz_U3D8WCfpit6l1Nkq1zht3U18vzI8I',
    appId: '1:49266914884:ios:d303749789029562392e11',
    messagingSenderId: '49266914884',
    projectId: 'secretcomms-6de0e',
    storageBucket: 'secretcomms-6de0e.appspot.com',
    iosBundleId: 'com.example.secretComms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ZraAHcikDfnDPcUN1UEdLrznxnvyANs',
    appId: '1:49266914884:web:846a583428ee961e392e11',
    messagingSenderId: '49266914884',
    projectId: 'secretcomms-6de0e',
    authDomain: 'secretcomms-6de0e.firebaseapp.com',
    storageBucket: 'secretcomms-6de0e.appspot.com',
    measurementId: 'G-2HCRH5WVPK',
  );
}
